<?php
/**
 * CMenu class file.
 * Author fang.yanliang
 * Data 2013-1-17
 */
Yii::import('zii.widgets.CMenu');

class CMMenu extends CMenu
{
	/**
	 * Checks whether a menu item is active.
	 * This is done by checking if the currently requested URL is generated by the 'url' option
	 * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
	 * @param array $item the menu item to be checked
	 * @param string $route the route of the current request
	 * @return boolean whether the menu item is active
	 */
	protected function isItemActive($item,$route)
	{
		//print_r($route);
		//echo "<br/>";
		//var_dump($item);
		//exit;
		//if(isset($item['url']) && is_array($item['url']) && !strcasecmp(trim($item['url'][0],'/'),$route))
		if(isset($item['url']) && is_array($item['url']) && strpos('/'.$route,trim($item['url'][0],'/'))>0)
		{
			if(count($item['url'])>=1)
			{
				foreach(array_splice($item['url'],1) as $name=>$value)
				{
					if(!isset($_GET[$name]) || $_GET[$name]!=$value)
						return false;
				}
			}
			return true;
		}elseif(isset($item['url']) && strlen(strstr($item['url'][0],$route)) >0){
			return true;
		}
		return false;
	}
}